#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

set +e

RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' 

echo -e "${CYAN}[Automated]${NC} Running pre-commit hook"

echo -e "${CYAN}[Automated]${NC} ${CYAN}Stylelinting files${NC}"
npm run lint:fix
npm run build

if [ $? -ne 0 ]; then
  echo -e "${RED}[Automated]${NC} ${RED}Stylelinting failed 💀${NC}"
  exit 1
fi
